version: '3'
services:
  review-service:
    image: opentelemetry/opentelemetry-review-service:latest
    ports:
      - "8082:8082"
    environment:
      - LOCALHOST_IP=$LOCALHOST_IP
  item-service:
    image: opentelemetry/opentelemetry-item-service:latest
    ports:
      - "8081:8081"
    environment:
      - LOCALHOST_IP=$LOCALHOST_IP
    depends_on:
      - "review-service"
  stock-service:
    image: opentelemetry/opentelemetry-stock-service:latest
    ports:
      - "8083:8083"
    environment:
      - LOCALHOST_IP=$LOCALHOST_IP
  product-service:
    image: opentelemetry/opentelemetry-product-service:latest
    ports:
      - "8080:8080"
    environment:
      - LOCALHOST_IP=$LOCALHOST_IP
    depends_on: 
      - "item-service"
      - "stock-service"